/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPlaygroundRouteImport } from './routes/admin/playground'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminKnowledgeBaseRouteImport } from './routes/admin/knowledge-base'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminActionsRouteImport } from './routes/admin/actions'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AdminChatHistoryIndexRouteImport } from './routes/admin/chat-history/index'
import { ServerRoute as ApiUploadServerRouteImport } from './routes/api/upload'
import { ServerRoute as ApiQuestionsServerRouteImport } from './routes/api/questions'
import { ServerRoute as ApiMyProductsServerRouteImport } from './routes/api/my-products'
import { ServerRoute as ApiMyLinksServerRouteImport } from './routes/api/my-links'
import { ServerRoute as ApiMyBrandingServerRouteImport } from './routes/api/my-branding'
import { ServerRoute as ApiHelloServerRouteImport } from './routes/api/hello'
import { ServerRoute as ApiGetOgInfoServerRouteImport } from './routes/api/get-og-info'
import { ServerRoute as ApiChatIndexServerRouteImport } from './routes/api/chat/index'
import { ServerRoute as ApiChatHistoryServerRouteImport } from './routes/api/chat/history'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const AdminTestLazyRouteImport = createFileRoute('/admin/test')()
const rootServerRouteImport = createServerRootRoute()

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestLazyRoute = AdminTestLazyRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/test.lazy').then((d) => d.Route))
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlaygroundRoute = AdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKnowledgeBaseRoute = AdminKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActionsRoute = AdminActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatHistoryIndexRoute = AdminChatHistoryIndexRouteImport.update({
  id: '/chat-history/',
  path: '/chat-history/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiUploadServerRoute = ApiUploadServerRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiQuestionsServerRoute = ApiQuestionsServerRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMyProductsServerRoute = ApiMyProductsServerRouteImport.update({
  id: '/api/my-products',
  path: '/api/my-products',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMyLinksServerRoute = ApiMyLinksServerRouteImport.update({
  id: '/api/my-links',
  path: '/api/my-links',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMyBrandingServerRoute = ApiMyBrandingServerRouteImport.update({
  id: '/api/my-branding',
  path: '/api/my-branding',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiHelloServerRoute = ApiHelloServerRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiGetOgInfoServerRoute = ApiGetOgInfoServerRouteImport.update({
  id: '/api/get-og-info',
  path: '/api/get-og-info',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiChatIndexServerRoute = ApiChatIndexServerRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiChatHistoryServerRoute = ApiChatHistoryServerRouteImport.update({
  id: '/api/chat/history',
  path: '/api/chat/history',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/test': typeof AdminTestLazyRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/chat-history': typeof AdminChatHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/test': typeof AdminTestLazyRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/chat-history': typeof AdminChatHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/test': typeof AdminTestLazyRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/chat-history/': typeof AdminChatHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/actions'
    | '/admin/analytics'
    | '/admin/knowledge-base'
    | '/admin/leads'
    | '/admin/overview'
    | '/admin/playground'
    | '/admin/settings'
    | '/admin/test'
    | '/onboarding'
    | '/admin/chat-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/actions'
    | '/admin/analytics'
    | '/admin/knowledge-base'
    | '/admin/leads'
    | '/admin/overview'
    | '/admin/playground'
    | '/admin/settings'
    | '/admin/test'
    | '/onboarding'
    | '/admin/chat-history'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/admin/actions'
    | '/admin/analytics'
    | '/admin/knowledge-base'
    | '/admin/leads'
    | '/admin/overview'
    | '/admin/playground'
    | '/admin/settings'
    | '/admin/test'
    | '/onboarding/'
    | '/admin/chat-history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/get-og-info': typeof ApiGetOgInfoServerRoute
  '/api/hello': typeof ApiHelloServerRoute
  '/api/my-branding': typeof ApiMyBrandingServerRoute
  '/api/my-links': typeof ApiMyLinksServerRoute
  '/api/my-products': typeof ApiMyProductsServerRoute
  '/api/questions': typeof ApiQuestionsServerRoute
  '/api/upload': typeof ApiUploadServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/chat/history': typeof ApiChatHistoryServerRoute
  '/api/chat': typeof ApiChatIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/get-og-info': typeof ApiGetOgInfoServerRoute
  '/api/hello': typeof ApiHelloServerRoute
  '/api/my-branding': typeof ApiMyBrandingServerRoute
  '/api/my-links': typeof ApiMyLinksServerRoute
  '/api/my-products': typeof ApiMyProductsServerRoute
  '/api/questions': typeof ApiQuestionsServerRoute
  '/api/upload': typeof ApiUploadServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/chat/history': typeof ApiChatHistoryServerRoute
  '/api/chat': typeof ApiChatIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/get-og-info': typeof ApiGetOgInfoServerRoute
  '/api/hello': typeof ApiHelloServerRoute
  '/api/my-branding': typeof ApiMyBrandingServerRoute
  '/api/my-links': typeof ApiMyLinksServerRoute
  '/api/my-products': typeof ApiMyProductsServerRoute
  '/api/questions': typeof ApiQuestionsServerRoute
  '/api/upload': typeof ApiUploadServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/chat/history': typeof ApiChatHistoryServerRoute
  '/api/chat/': typeof ApiChatIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/get-og-info'
    | '/api/hello'
    | '/api/my-branding'
    | '/api/my-links'
    | '/api/my-products'
    | '/api/questions'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/chat/history'
    | '/api/chat'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/get-og-info'
    | '/api/hello'
    | '/api/my-branding'
    | '/api/my-links'
    | '/api/my-products'
    | '/api/questions'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/chat/history'
    | '/api/chat'
  id:
    | '__root__'
    | '/api/get-og-info'
    | '/api/hello'
    | '/api/my-branding'
    | '/api/my-links'
    | '/api/my-products'
    | '/api/questions'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/chat/history'
    | '/api/chat/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiGetOgInfoServerRoute: typeof ApiGetOgInfoServerRoute
  ApiHelloServerRoute: typeof ApiHelloServerRoute
  ApiMyBrandingServerRoute: typeof ApiMyBrandingServerRoute
  ApiMyLinksServerRoute: typeof ApiMyLinksServerRoute
  ApiMyProductsServerRoute: typeof ApiMyProductsServerRoute
  ApiQuestionsServerRoute: typeof ApiQuestionsServerRoute
  ApiUploadServerRoute: typeof ApiUploadServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiChatHistoryServerRoute: typeof ApiChatHistoryServerRoute
  ApiChatIndexServerRoute: typeof ApiChatIndexServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/test': {
      id: '/admin/test'
      path: '/test'
      fullPath: '/admin/test'
      preLoaderRoute: typeof AdminTestLazyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/playground': {
      id: '/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AdminPlaygroundRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/knowledge-base': {
      id: '/admin/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AdminKnowledgeBaseRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat-history/': {
      id: '/admin/chat-history/'
      path: '/chat-history'
      fullPath: '/admin/chat-history'
      preLoaderRoute: typeof AdminChatHistoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/my-products': {
      id: '/api/my-products'
      path: '/api/my-products'
      fullPath: '/api/my-products'
      preLoaderRoute: typeof ApiMyProductsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/my-links': {
      id: '/api/my-links'
      path: '/api/my-links'
      fullPath: '/api/my-links'
      preLoaderRoute: typeof ApiMyLinksServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/my-branding': {
      id: '/api/my-branding'
      path: '/api/my-branding'
      fullPath: '/api/my-branding'
      preLoaderRoute: typeof ApiMyBrandingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/get-og-info': {
      id: '/api/get-og-info'
      path: '/api/get-og-info'
      fullPath: '/api/get-og-info'
      preLoaderRoute: typeof ApiGetOgInfoServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/chat/history': {
      id: '/api/chat/history'
      path: '/api/chat/history'
      fullPath: '/api/chat/history'
      preLoaderRoute: typeof ApiChatHistoryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminActionsRoute: typeof AdminActionsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminKnowledgeBaseRoute: typeof AdminKnowledgeBaseRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPlaygroundRoute: typeof AdminPlaygroundRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestLazyRoute: typeof AdminTestLazyRoute
  AdminChatHistoryIndexRoute: typeof AdminChatHistoryIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActionsRoute: AdminActionsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminKnowledgeBaseRoute: AdminKnowledgeBaseRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPlaygroundRoute: AdminPlaygroundRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestLazyRoute: AdminTestLazyRoute,
  AdminChatHistoryIndexRoute: AdminChatHistoryIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiGetOgInfoServerRoute: ApiGetOgInfoServerRoute,
  ApiHelloServerRoute: ApiHelloServerRoute,
  ApiMyBrandingServerRoute: ApiMyBrandingServerRoute,
  ApiMyLinksServerRoute: ApiMyLinksServerRoute,
  ApiMyProductsServerRoute: ApiMyProductsServerRoute,
  ApiQuestionsServerRoute: ApiQuestionsServerRoute,
  ApiUploadServerRoute: ApiUploadServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiChatHistoryServerRoute: ApiChatHistoryServerRoute,
  ApiChatIndexServerRoute: ApiChatIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
