/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ChoosePlanRouteImport } from './routes/choose-plan'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as TalkPageIdRouteImport } from './routes/talk/$pageId'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as BubbleWidgetIdRouteImport } from './routes/bubble/$widgetId'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPlaygroundRouteImport } from './routes/admin/playground'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminKnowledgeBaseRouteImport } from './routes/admin/knowledge-base'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AdminChatHistoryIndexRouteImport } from './routes/admin/chat-history/index'
import { Route as AdminActivityIndexRouteImport } from './routes/admin/activity/index'
import { Route as AdminActionsIndexRouteImport } from './routes/admin/actions/index'
import { Route as AdminActionsNewActionRouteImport } from './routes/admin/actions/new-action'
import { Route as AdminActionsEditActionRouteImport } from './routes/admin/actions/edit-action'
import { ServerRoute as ApiVoteCountServerRouteImport } from './routes/api/vote-count'
import { ServerRoute as ApiVoteServerRouteImport } from './routes/api/vote'
import { ServerRoute as ApiVisitorAnalyticsServerRouteImport } from './routes/api/visitor-analytics'
import { ServerRoute as ApiUploadImagesServerRouteImport } from './routes/api/upload-images'
import { ServerRoute as ApiUploadDocumentsServerRouteImport } from './routes/api/upload-documents'
import { ServerRoute as ApiUpdateChatStatusServerRouteImport } from './routes/api/update-chat-status'
import { ServerRoute as ApiTrainingStatusServerRouteImport } from './routes/api/training-status'
import { ServerRoute as ApiTrainAgentServerRouteImport } from './routes/api/train-agent'
import { ServerRoute as ApiTextSourcesServerRouteImport } from './routes/api/text-sources'
import { ServerRoute as ApiSimilaritySearchServerRouteImport } from './routes/api/similarity-search'
import { ServerRoute as ApiSetActiveChatbotServerRouteImport } from './routes/api/set-active-chatbot'
import { ServerRoute as ApiScrapeServerRouteImport } from './routes/api/scrape'
import { ServerRoute as ApiReportIssueServerRouteImport } from './routes/api/report-issue'
import { ServerRoute as ApiQuestionsServerRouteImport } from './routes/api/questions'
import { ServerRoute as ApiOgServerRouteImport } from './routes/api/og'
import { ServerRoute as ApiMyChatbotServerRouteImport } from './routes/api/my-chatbot'
import { ServerRoute as ApiLeadsServerRouteImport } from './routes/api/leads'
import { ServerRoute as ApiInviteMemberServerRouteImport } from './routes/api/invite-member'
import { ServerRoute as ApiHelloServerRouteImport } from './routes/api/hello'
import { ServerRoute as ApiFirecrawlWebhookServerRouteImport } from './routes/api/firecrawl-webhook'
import { ServerRoute as ApiFeedbackServerRouteImport } from './routes/api/feedback'
import { ServerRoute as ApiDocumentSourceServerRouteImport } from './routes/api/document-source'
import { ServerRoute as ApiCrawlServerRouteImport } from './routes/api/crawl'
import { ServerRoute as ApiCheckoutServerRouteImport } from './routes/api/checkout'
import { ServerRoute as ApiChatbotsServerRouteImport } from './routes/api/chatbots'
import { ServerRoute as ApiChatbotCountServerRouteImport } from './routes/api/chatbot-count'
import { ServerRoute as ApiAnalyticsStreamServerRouteImport } from './routes/api/analytics-stream'
import { ServerRoute as ApiChatIndexServerRouteImport } from './routes/api/chat/index'
import { ServerRoute as ApiAgentActionsIndexServerRouteImport } from './routes/api/agent-actions/index'
import { ServerRoute as ApiActivityIndexServerRouteImport } from './routes/api/activity/index'
import { ServerRoute as IntegrationsCalendlyCallbackServerRouteImport } from './routes/integrations/calendly/callback'
import { ServerRoute as ApiWebhookPolarServerRouteImport } from './routes/api/webhook/polar'
import { ServerRoute as ApiSourcesCountServerRouteImport } from './routes/api/sources/count'
import { ServerRoute as ApiEmbedGenerateTokenServerRouteImport } from './routes/api/embed/generate-token'
import { ServerRoute as ApiChatHistoryServerRouteImport } from './routes/api/chat/history'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'
import { ServerRoute as ApiAgentActionsActionIdServerRouteImport } from './routes/api/agent-actions/$actionId'
import { ServerRoute as ApiActivityActivityIdServerRouteImport } from './routes/api/activity/$activityId'
import { ServerRoute as ApiAcceptInvitationInvitationIdServerRouteImport } from './routes/api/accept-invitation/$invitationId'
import { ServerRoute as ApiEmbedChatbotIdentifierServerRouteImport } from './routes/api/embed/chatbot/$identifier'
import { ServerRoute as ApiEmbedChatPlatformIdentifierServerRouteImport } from './routes/api/embed/chat/$platformIdentifier'
import { ServerRoute as ApiIntegrationsCalendlySettingsChatbotIdServerRouteImport } from './routes/api/integrations/calendly/settings/$chatbotId'
import { ServerRoute as ApiIntegrationsCalendlyAuthRefreshServerRouteImport } from './routes/api/integrations/calendly/auth/refresh'
import { ServerRoute as ApiIntegrationsCalendlyAuthDisconnectServerRouteImport } from './routes/api/integrations/calendly/auth/disconnect'
import { ServerRoute as ApiIntegrationsCalendlyAuthConnectServerRouteImport } from './routes/api/integrations/calendly/auth/connect'

const rootServerRouteImport = createServerRootRoute()

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoosePlanRoute = ChoosePlanRouteImport.update({
  id: '/choose-plan',
  path: '/choose-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkPageIdRoute = TalkPageIdRouteImport.update({
  id: '/talk/$pageId',
  path: '/talk/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BubbleWidgetIdRoute = BubbleWidgetIdRouteImport.update({
  id: '/bubble/$widgetId',
  path: '/bubble/$widgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlaygroundRoute = AdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKnowledgeBaseRoute = AdminKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatHistoryIndexRoute = AdminChatHistoryIndexRouteImport.update({
  id: '/chat-history/',
  path: '/chat-history/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityIndexRoute = AdminActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActionsIndexRoute = AdminActionsIndexRouteImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActionsNewActionRoute = AdminActionsNewActionRouteImport.update({
  id: '/actions/new-action',
  path: '/actions/new-action',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActionsEditActionRoute = AdminActionsEditActionRouteImport.update({
  id: '/actions/edit-action',
  path: '/actions/edit-action',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiVoteCountServerRoute = ApiVoteCountServerRouteImport.update({
  id: '/api/vote-count',
  path: '/api/vote-count',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiVoteServerRoute = ApiVoteServerRouteImport.update({
  id: '/api/vote',
  path: '/api/vote',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiVisitorAnalyticsServerRoute =
  ApiVisitorAnalyticsServerRouteImport.update({
    id: '/api/visitor-analytics',
    path: '/api/visitor-analytics',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiUploadImagesServerRoute = ApiUploadImagesServerRouteImport.update({
  id: '/api/upload-images',
  path: '/api/upload-images',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUploadDocumentsServerRoute =
  ApiUploadDocumentsServerRouteImport.update({
    id: '/api/upload-documents',
    path: '/api/upload-documents',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiUpdateChatStatusServerRoute =
  ApiUpdateChatStatusServerRouteImport.update({
    id: '/api/update-chat-status',
    path: '/api/update-chat-status',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTrainingStatusServerRoute = ApiTrainingStatusServerRouteImport.update({
  id: '/api/training-status',
  path: '/api/training-status',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTrainAgentServerRoute = ApiTrainAgentServerRouteImport.update({
  id: '/api/train-agent',
  path: '/api/train-agent',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTextSourcesServerRoute = ApiTextSourcesServerRouteImport.update({
  id: '/api/text-sources',
  path: '/api/text-sources',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiSimilaritySearchServerRoute =
  ApiSimilaritySearchServerRouteImport.update({
    id: '/api/similarity-search',
    path: '/api/similarity-search',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiSetActiveChatbotServerRoute =
  ApiSetActiveChatbotServerRouteImport.update({
    id: '/api/set-active-chatbot',
    path: '/api/set-active-chatbot',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiScrapeServerRoute = ApiScrapeServerRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiReportIssueServerRoute = ApiReportIssueServerRouteImport.update({
  id: '/api/report-issue',
  path: '/api/report-issue',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiQuestionsServerRoute = ApiQuestionsServerRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiOgServerRoute = ApiOgServerRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMyChatbotServerRoute = ApiMyChatbotServerRouteImport.update({
  id: '/api/my-chatbot',
  path: '/api/my-chatbot',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiLeadsServerRoute = ApiLeadsServerRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiInviteMemberServerRoute = ApiInviteMemberServerRouteImport.update({
  id: '/api/invite-member',
  path: '/api/invite-member',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiHelloServerRoute = ApiHelloServerRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiFirecrawlWebhookServerRoute =
  ApiFirecrawlWebhookServerRouteImport.update({
    id: '/api/firecrawl-webhook',
    path: '/api/firecrawl-webhook',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiFeedbackServerRoute = ApiFeedbackServerRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiDocumentSourceServerRoute = ApiDocumentSourceServerRouteImport.update({
  id: '/api/document-source',
  path: '/api/document-source',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiCrawlServerRoute = ApiCrawlServerRouteImport.update({
  id: '/api/crawl',
  path: '/api/crawl',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiCheckoutServerRoute = ApiCheckoutServerRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiChatbotsServerRoute = ApiChatbotsServerRouteImport.update({
  id: '/api/chatbots',
  path: '/api/chatbots',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiChatbotCountServerRoute = ApiChatbotCountServerRouteImport.update({
  id: '/api/chatbot-count',
  path: '/api/chatbot-count',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAnalyticsStreamServerRoute =
  ApiAnalyticsStreamServerRouteImport.update({
    id: '/api/analytics-stream',
    path: '/api/analytics-stream',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiChatIndexServerRoute = ApiChatIndexServerRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAgentActionsIndexServerRoute =
  ApiAgentActionsIndexServerRouteImport.update({
    id: '/api/agent-actions/',
    path: '/api/agent-actions/',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiActivityIndexServerRoute = ApiActivityIndexServerRouteImport.update({
  id: '/api/activity/',
  path: '/api/activity/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const IntegrationsCalendlyCallbackServerRoute =
  IntegrationsCalendlyCallbackServerRouteImport.update({
    id: '/integrations/calendly/callback',
    path: '/integrations/calendly/callback',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiWebhookPolarServerRoute = ApiWebhookPolarServerRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiSourcesCountServerRoute = ApiSourcesCountServerRouteImport.update({
  id: '/api/sources/count',
  path: '/api/sources/count',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiEmbedGenerateTokenServerRoute =
  ApiEmbedGenerateTokenServerRouteImport.update({
    id: '/api/embed/generate-token',
    path: '/api/embed/generate-token',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiChatHistoryServerRoute = ApiChatHistoryServerRouteImport.update({
  id: '/api/chat/history',
  path: '/api/chat/history',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAgentActionsActionIdServerRoute =
  ApiAgentActionsActionIdServerRouteImport.update({
    id: '/api/agent-actions/$actionId',
    path: '/api/agent-actions/$actionId',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiActivityActivityIdServerRoute =
  ApiActivityActivityIdServerRouteImport.update({
    id: '/api/activity/$activityId',
    path: '/api/activity/$activityId',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAcceptInvitationInvitationIdServerRoute =
  ApiAcceptInvitationInvitationIdServerRouteImport.update({
    id: '/api/accept-invitation/$invitationId',
    path: '/api/accept-invitation/$invitationId',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiEmbedChatbotIdentifierServerRoute =
  ApiEmbedChatbotIdentifierServerRouteImport.update({
    id: '/api/embed/chatbot/$identifier',
    path: '/api/embed/chatbot/$identifier',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiEmbedChatPlatformIdentifierServerRoute =
  ApiEmbedChatPlatformIdentifierServerRouteImport.update({
    id: '/api/embed/chat/$platformIdentifier',
    path: '/api/embed/chat/$platformIdentifier',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiIntegrationsCalendlySettingsChatbotIdServerRoute =
  ApiIntegrationsCalendlySettingsChatbotIdServerRouteImport.update({
    id: '/api/integrations/calendly/settings/$chatbotId',
    path: '/api/integrations/calendly/settings/$chatbotId',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiIntegrationsCalendlyAuthRefreshServerRoute =
  ApiIntegrationsCalendlyAuthRefreshServerRouteImport.update({
    id: '/api/integrations/calendly/auth/refresh',
    path: '/api/integrations/calendly/auth/refresh',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiIntegrationsCalendlyAuthDisconnectServerRoute =
  ApiIntegrationsCalendlyAuthDisconnectServerRouteImport.update({
    id: '/api/integrations/calendly/auth/disconnect',
    path: '/api/integrations/calendly/auth/disconnect',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiIntegrationsCalendlyAuthConnectServerRoute =
  ApiIntegrationsCalendlyAuthConnectServerRouteImport.update({
    id: '/api/integrations/calendly/auth/connect',
    path: '/api/integrations/calendly/auth/connect',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/success': typeof SuccessRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/setup': typeof authSetupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/bubble/$widgetId': typeof BubbleWidgetIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/talk/$pageId': typeof TalkPageIdRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/actions/edit-action': typeof AdminActionsEditActionRoute
  '/admin/actions/new-action': typeof AdminActionsNewActionRoute
  '/admin/actions': typeof AdminActionsIndexRoute
  '/admin/activity': typeof AdminActivityIndexRoute
  '/admin/chat-history': typeof AdminChatHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/success': typeof SuccessRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/setup': typeof authSetupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/bubble/$widgetId': typeof BubbleWidgetIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/talk/$pageId': typeof TalkPageIdRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/actions/edit-action': typeof AdminActionsEditActionRoute
  '/admin/actions/new-action': typeof AdminActionsNewActionRoute
  '/admin/actions': typeof AdminActionsIndexRoute
  '/admin/activity': typeof AdminActivityIndexRoute
  '/admin/chat-history': typeof AdminChatHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/success': typeof SuccessRoute
  '/test': typeof TestRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/setup': typeof authSetupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/bubble/$widgetId': typeof BubbleWidgetIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/talk/$pageId': typeof TalkPageIdRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/actions/edit-action': typeof AdminActionsEditActionRoute
  '/admin/actions/new-action': typeof AdminActionsNewActionRoute
  '/admin/actions/': typeof AdminActionsIndexRoute
  '/admin/activity/': typeof AdminActivityIndexRoute
  '/admin/chat-history/': typeof AdminChatHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/accept-invitation'
    | '/choose-plan'
    | '/success'
    | '/test'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/knowledge-base'
    | '/admin/leads'
    | '/admin/overview'
    | '/admin/playground'
    | '/admin/settings'
    | '/bubble/$widgetId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/talk/$pageId'
    | '/onboarding'
    | '/admin/actions/edit-action'
    | '/admin/actions/new-action'
    | '/admin/actions'
    | '/admin/activity'
    | '/admin/chat-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/accept-invitation'
    | '/choose-plan'
    | '/success'
    | '/test'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/knowledge-base'
    | '/admin/leads'
    | '/admin/overview'
    | '/admin/playground'
    | '/admin/settings'
    | '/bubble/$widgetId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/talk/$pageId'
    | '/onboarding'
    | '/admin/actions/edit-action'
    | '/admin/actions/new-action'
    | '/admin/actions'
    | '/admin/activity'
    | '/admin/chat-history'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/accept-invitation'
    | '/choose-plan'
    | '/success'
    | '/test'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/setup'
    | '/(auth)/verify-email'
    | '/admin/analytics'
    | '/admin/knowledge-base'
    | '/admin/leads'
    | '/admin/overview'
    | '/admin/playground'
    | '/admin/settings'
    | '/bubble/$widgetId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/talk/$pageId'
    | '/onboarding/'
    | '/admin/actions/edit-action'
    | '/admin/actions/new-action'
    | '/admin/actions/'
    | '/admin/activity/'
    | '/admin/chat-history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ChoosePlanRoute: typeof ChoosePlanRoute
  SuccessRoute: typeof SuccessRoute
  TestRoute: typeof TestRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSetupRoute: typeof authSetupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  BubbleWidgetIdRoute: typeof BubbleWidgetIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  TalkPageIdRoute: typeof TalkPageIdRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/analytics-stream': typeof ApiAnalyticsStreamServerRoute
  '/api/chatbot-count': typeof ApiChatbotCountServerRoute
  '/api/chatbots': typeof ApiChatbotsServerRoute
  '/api/checkout': typeof ApiCheckoutServerRoute
  '/api/crawl': typeof ApiCrawlServerRoute
  '/api/document-source': typeof ApiDocumentSourceServerRoute
  '/api/feedback': typeof ApiFeedbackServerRoute
  '/api/firecrawl-webhook': typeof ApiFirecrawlWebhookServerRoute
  '/api/hello': typeof ApiHelloServerRoute
  '/api/invite-member': typeof ApiInviteMemberServerRoute
  '/api/leads': typeof ApiLeadsServerRoute
  '/api/my-chatbot': typeof ApiMyChatbotServerRoute
  '/api/og': typeof ApiOgServerRoute
  '/api/questions': typeof ApiQuestionsServerRoute
  '/api/report-issue': typeof ApiReportIssueServerRoute
  '/api/scrape': typeof ApiScrapeServerRoute
  '/api/set-active-chatbot': typeof ApiSetActiveChatbotServerRoute
  '/api/similarity-search': typeof ApiSimilaritySearchServerRoute
  '/api/text-sources': typeof ApiTextSourcesServerRoute
  '/api/train-agent': typeof ApiTrainAgentServerRoute
  '/api/training-status': typeof ApiTrainingStatusServerRoute
  '/api/update-chat-status': typeof ApiUpdateChatStatusServerRoute
  '/api/upload-documents': typeof ApiUploadDocumentsServerRoute
  '/api/upload-images': typeof ApiUploadImagesServerRoute
  '/api/visitor-analytics': typeof ApiVisitorAnalyticsServerRoute
  '/api/vote': typeof ApiVoteServerRoute
  '/api/vote-count': typeof ApiVoteCountServerRoute
  '/api/accept-invitation/$invitationId': typeof ApiAcceptInvitationInvitationIdServerRoute
  '/api/activity/$activityId': typeof ApiActivityActivityIdServerRoute
  '/api/agent-actions/$actionId': typeof ApiAgentActionsActionIdServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/chat/history': typeof ApiChatHistoryServerRoute
  '/api/embed/generate-token': typeof ApiEmbedGenerateTokenServerRoute
  '/api/sources/count': typeof ApiSourcesCountServerRoute
  '/api/webhook/polar': typeof ApiWebhookPolarServerRoute
  '/integrations/calendly/callback': typeof IntegrationsCalendlyCallbackServerRoute
  '/api/activity': typeof ApiActivityIndexServerRoute
  '/api/agent-actions': typeof ApiAgentActionsIndexServerRoute
  '/api/chat': typeof ApiChatIndexServerRoute
  '/api/embed/chat/$platformIdentifier': typeof ApiEmbedChatPlatformIdentifierServerRoute
  '/api/embed/chatbot/$identifier': typeof ApiEmbedChatbotIdentifierServerRoute
  '/api/integrations/calendly/auth/connect': typeof ApiIntegrationsCalendlyAuthConnectServerRoute
  '/api/integrations/calendly/auth/disconnect': typeof ApiIntegrationsCalendlyAuthDisconnectServerRoute
  '/api/integrations/calendly/auth/refresh': typeof ApiIntegrationsCalendlyAuthRefreshServerRoute
  '/api/integrations/calendly/settings/$chatbotId': typeof ApiIntegrationsCalendlySettingsChatbotIdServerRoute
}
export interface FileServerRoutesByTo {
  '/api/analytics-stream': typeof ApiAnalyticsStreamServerRoute
  '/api/chatbot-count': typeof ApiChatbotCountServerRoute
  '/api/chatbots': typeof ApiChatbotsServerRoute
  '/api/checkout': typeof ApiCheckoutServerRoute
  '/api/crawl': typeof ApiCrawlServerRoute
  '/api/document-source': typeof ApiDocumentSourceServerRoute
  '/api/feedback': typeof ApiFeedbackServerRoute
  '/api/firecrawl-webhook': typeof ApiFirecrawlWebhookServerRoute
  '/api/hello': typeof ApiHelloServerRoute
  '/api/invite-member': typeof ApiInviteMemberServerRoute
  '/api/leads': typeof ApiLeadsServerRoute
  '/api/my-chatbot': typeof ApiMyChatbotServerRoute
  '/api/og': typeof ApiOgServerRoute
  '/api/questions': typeof ApiQuestionsServerRoute
  '/api/report-issue': typeof ApiReportIssueServerRoute
  '/api/scrape': typeof ApiScrapeServerRoute
  '/api/set-active-chatbot': typeof ApiSetActiveChatbotServerRoute
  '/api/similarity-search': typeof ApiSimilaritySearchServerRoute
  '/api/text-sources': typeof ApiTextSourcesServerRoute
  '/api/train-agent': typeof ApiTrainAgentServerRoute
  '/api/training-status': typeof ApiTrainingStatusServerRoute
  '/api/update-chat-status': typeof ApiUpdateChatStatusServerRoute
  '/api/upload-documents': typeof ApiUploadDocumentsServerRoute
  '/api/upload-images': typeof ApiUploadImagesServerRoute
  '/api/visitor-analytics': typeof ApiVisitorAnalyticsServerRoute
  '/api/vote': typeof ApiVoteServerRoute
  '/api/vote-count': typeof ApiVoteCountServerRoute
  '/api/accept-invitation/$invitationId': typeof ApiAcceptInvitationInvitationIdServerRoute
  '/api/activity/$activityId': typeof ApiActivityActivityIdServerRoute
  '/api/agent-actions/$actionId': typeof ApiAgentActionsActionIdServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/chat/history': typeof ApiChatHistoryServerRoute
  '/api/embed/generate-token': typeof ApiEmbedGenerateTokenServerRoute
  '/api/sources/count': typeof ApiSourcesCountServerRoute
  '/api/webhook/polar': typeof ApiWebhookPolarServerRoute
  '/integrations/calendly/callback': typeof IntegrationsCalendlyCallbackServerRoute
  '/api/activity': typeof ApiActivityIndexServerRoute
  '/api/agent-actions': typeof ApiAgentActionsIndexServerRoute
  '/api/chat': typeof ApiChatIndexServerRoute
  '/api/embed/chat/$platformIdentifier': typeof ApiEmbedChatPlatformIdentifierServerRoute
  '/api/embed/chatbot/$identifier': typeof ApiEmbedChatbotIdentifierServerRoute
  '/api/integrations/calendly/auth/connect': typeof ApiIntegrationsCalendlyAuthConnectServerRoute
  '/api/integrations/calendly/auth/disconnect': typeof ApiIntegrationsCalendlyAuthDisconnectServerRoute
  '/api/integrations/calendly/auth/refresh': typeof ApiIntegrationsCalendlyAuthRefreshServerRoute
  '/api/integrations/calendly/settings/$chatbotId': typeof ApiIntegrationsCalendlySettingsChatbotIdServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/analytics-stream': typeof ApiAnalyticsStreamServerRoute
  '/api/chatbot-count': typeof ApiChatbotCountServerRoute
  '/api/chatbots': typeof ApiChatbotsServerRoute
  '/api/checkout': typeof ApiCheckoutServerRoute
  '/api/crawl': typeof ApiCrawlServerRoute
  '/api/document-source': typeof ApiDocumentSourceServerRoute
  '/api/feedback': typeof ApiFeedbackServerRoute
  '/api/firecrawl-webhook': typeof ApiFirecrawlWebhookServerRoute
  '/api/hello': typeof ApiHelloServerRoute
  '/api/invite-member': typeof ApiInviteMemberServerRoute
  '/api/leads': typeof ApiLeadsServerRoute
  '/api/my-chatbot': typeof ApiMyChatbotServerRoute
  '/api/og': typeof ApiOgServerRoute
  '/api/questions': typeof ApiQuestionsServerRoute
  '/api/report-issue': typeof ApiReportIssueServerRoute
  '/api/scrape': typeof ApiScrapeServerRoute
  '/api/set-active-chatbot': typeof ApiSetActiveChatbotServerRoute
  '/api/similarity-search': typeof ApiSimilaritySearchServerRoute
  '/api/text-sources': typeof ApiTextSourcesServerRoute
  '/api/train-agent': typeof ApiTrainAgentServerRoute
  '/api/training-status': typeof ApiTrainingStatusServerRoute
  '/api/update-chat-status': typeof ApiUpdateChatStatusServerRoute
  '/api/upload-documents': typeof ApiUploadDocumentsServerRoute
  '/api/upload-images': typeof ApiUploadImagesServerRoute
  '/api/visitor-analytics': typeof ApiVisitorAnalyticsServerRoute
  '/api/vote': typeof ApiVoteServerRoute
  '/api/vote-count': typeof ApiVoteCountServerRoute
  '/api/accept-invitation/$invitationId': typeof ApiAcceptInvitationInvitationIdServerRoute
  '/api/activity/$activityId': typeof ApiActivityActivityIdServerRoute
  '/api/agent-actions/$actionId': typeof ApiAgentActionsActionIdServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/chat/history': typeof ApiChatHistoryServerRoute
  '/api/embed/generate-token': typeof ApiEmbedGenerateTokenServerRoute
  '/api/sources/count': typeof ApiSourcesCountServerRoute
  '/api/webhook/polar': typeof ApiWebhookPolarServerRoute
  '/integrations/calendly/callback': typeof IntegrationsCalendlyCallbackServerRoute
  '/api/activity/': typeof ApiActivityIndexServerRoute
  '/api/agent-actions/': typeof ApiAgentActionsIndexServerRoute
  '/api/chat/': typeof ApiChatIndexServerRoute
  '/api/embed/chat/$platformIdentifier': typeof ApiEmbedChatPlatformIdentifierServerRoute
  '/api/embed/chatbot/$identifier': typeof ApiEmbedChatbotIdentifierServerRoute
  '/api/integrations/calendly/auth/connect': typeof ApiIntegrationsCalendlyAuthConnectServerRoute
  '/api/integrations/calendly/auth/disconnect': typeof ApiIntegrationsCalendlyAuthDisconnectServerRoute
  '/api/integrations/calendly/auth/refresh': typeof ApiIntegrationsCalendlyAuthRefreshServerRoute
  '/api/integrations/calendly/settings/$chatbotId': typeof ApiIntegrationsCalendlySettingsChatbotIdServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/analytics-stream'
    | '/api/chatbot-count'
    | '/api/chatbots'
    | '/api/checkout'
    | '/api/crawl'
    | '/api/document-source'
    | '/api/feedback'
    | '/api/firecrawl-webhook'
    | '/api/hello'
    | '/api/invite-member'
    | '/api/leads'
    | '/api/my-chatbot'
    | '/api/og'
    | '/api/questions'
    | '/api/report-issue'
    | '/api/scrape'
    | '/api/set-active-chatbot'
    | '/api/similarity-search'
    | '/api/text-sources'
    | '/api/train-agent'
    | '/api/training-status'
    | '/api/update-chat-status'
    | '/api/upload-documents'
    | '/api/upload-images'
    | '/api/visitor-analytics'
    | '/api/vote'
    | '/api/vote-count'
    | '/api/accept-invitation/$invitationId'
    | '/api/activity/$activityId'
    | '/api/agent-actions/$actionId'
    | '/api/auth/$'
    | '/api/chat/history'
    | '/api/embed/generate-token'
    | '/api/sources/count'
    | '/api/webhook/polar'
    | '/integrations/calendly/callback'
    | '/api/activity'
    | '/api/agent-actions'
    | '/api/chat'
    | '/api/embed/chat/$platformIdentifier'
    | '/api/embed/chatbot/$identifier'
    | '/api/integrations/calendly/auth/connect'
    | '/api/integrations/calendly/auth/disconnect'
    | '/api/integrations/calendly/auth/refresh'
    | '/api/integrations/calendly/settings/$chatbotId'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/analytics-stream'
    | '/api/chatbot-count'
    | '/api/chatbots'
    | '/api/checkout'
    | '/api/crawl'
    | '/api/document-source'
    | '/api/feedback'
    | '/api/firecrawl-webhook'
    | '/api/hello'
    | '/api/invite-member'
    | '/api/leads'
    | '/api/my-chatbot'
    | '/api/og'
    | '/api/questions'
    | '/api/report-issue'
    | '/api/scrape'
    | '/api/set-active-chatbot'
    | '/api/similarity-search'
    | '/api/text-sources'
    | '/api/train-agent'
    | '/api/training-status'
    | '/api/update-chat-status'
    | '/api/upload-documents'
    | '/api/upload-images'
    | '/api/visitor-analytics'
    | '/api/vote'
    | '/api/vote-count'
    | '/api/accept-invitation/$invitationId'
    | '/api/activity/$activityId'
    | '/api/agent-actions/$actionId'
    | '/api/auth/$'
    | '/api/chat/history'
    | '/api/embed/generate-token'
    | '/api/sources/count'
    | '/api/webhook/polar'
    | '/integrations/calendly/callback'
    | '/api/activity'
    | '/api/agent-actions'
    | '/api/chat'
    | '/api/embed/chat/$platformIdentifier'
    | '/api/embed/chatbot/$identifier'
    | '/api/integrations/calendly/auth/connect'
    | '/api/integrations/calendly/auth/disconnect'
    | '/api/integrations/calendly/auth/refresh'
    | '/api/integrations/calendly/settings/$chatbotId'
  id:
    | '__root__'
    | '/api/analytics-stream'
    | '/api/chatbot-count'
    | '/api/chatbots'
    | '/api/checkout'
    | '/api/crawl'
    | '/api/document-source'
    | '/api/feedback'
    | '/api/firecrawl-webhook'
    | '/api/hello'
    | '/api/invite-member'
    | '/api/leads'
    | '/api/my-chatbot'
    | '/api/og'
    | '/api/questions'
    | '/api/report-issue'
    | '/api/scrape'
    | '/api/set-active-chatbot'
    | '/api/similarity-search'
    | '/api/text-sources'
    | '/api/train-agent'
    | '/api/training-status'
    | '/api/update-chat-status'
    | '/api/upload-documents'
    | '/api/upload-images'
    | '/api/visitor-analytics'
    | '/api/vote'
    | '/api/vote-count'
    | '/api/accept-invitation/$invitationId'
    | '/api/activity/$activityId'
    | '/api/agent-actions/$actionId'
    | '/api/auth/$'
    | '/api/chat/history'
    | '/api/embed/generate-token'
    | '/api/sources/count'
    | '/api/webhook/polar'
    | '/integrations/calendly/callback'
    | '/api/activity/'
    | '/api/agent-actions/'
    | '/api/chat/'
    | '/api/embed/chat/$platformIdentifier'
    | '/api/embed/chatbot/$identifier'
    | '/api/integrations/calendly/auth/connect'
    | '/api/integrations/calendly/auth/disconnect'
    | '/api/integrations/calendly/auth/refresh'
    | '/api/integrations/calendly/settings/$chatbotId'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAnalyticsStreamServerRoute: typeof ApiAnalyticsStreamServerRoute
  ApiChatbotCountServerRoute: typeof ApiChatbotCountServerRoute
  ApiChatbotsServerRoute: typeof ApiChatbotsServerRoute
  ApiCheckoutServerRoute: typeof ApiCheckoutServerRoute
  ApiCrawlServerRoute: typeof ApiCrawlServerRoute
  ApiDocumentSourceServerRoute: typeof ApiDocumentSourceServerRoute
  ApiFeedbackServerRoute: typeof ApiFeedbackServerRoute
  ApiFirecrawlWebhookServerRoute: typeof ApiFirecrawlWebhookServerRoute
  ApiHelloServerRoute: typeof ApiHelloServerRoute
  ApiInviteMemberServerRoute: typeof ApiInviteMemberServerRoute
  ApiLeadsServerRoute: typeof ApiLeadsServerRoute
  ApiMyChatbotServerRoute: typeof ApiMyChatbotServerRoute
  ApiOgServerRoute: typeof ApiOgServerRoute
  ApiQuestionsServerRoute: typeof ApiQuestionsServerRoute
  ApiReportIssueServerRoute: typeof ApiReportIssueServerRoute
  ApiScrapeServerRoute: typeof ApiScrapeServerRoute
  ApiSetActiveChatbotServerRoute: typeof ApiSetActiveChatbotServerRoute
  ApiSimilaritySearchServerRoute: typeof ApiSimilaritySearchServerRoute
  ApiTextSourcesServerRoute: typeof ApiTextSourcesServerRoute
  ApiTrainAgentServerRoute: typeof ApiTrainAgentServerRoute
  ApiTrainingStatusServerRoute: typeof ApiTrainingStatusServerRoute
  ApiUpdateChatStatusServerRoute: typeof ApiUpdateChatStatusServerRoute
  ApiUploadDocumentsServerRoute: typeof ApiUploadDocumentsServerRoute
  ApiUploadImagesServerRoute: typeof ApiUploadImagesServerRoute
  ApiVisitorAnalyticsServerRoute: typeof ApiVisitorAnalyticsServerRoute
  ApiVoteServerRoute: typeof ApiVoteServerRoute
  ApiVoteCountServerRoute: typeof ApiVoteCountServerRoute
  ApiAcceptInvitationInvitationIdServerRoute: typeof ApiAcceptInvitationInvitationIdServerRoute
  ApiActivityActivityIdServerRoute: typeof ApiActivityActivityIdServerRoute
  ApiAgentActionsActionIdServerRoute: typeof ApiAgentActionsActionIdServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiChatHistoryServerRoute: typeof ApiChatHistoryServerRoute
  ApiEmbedGenerateTokenServerRoute: typeof ApiEmbedGenerateTokenServerRoute
  ApiSourcesCountServerRoute: typeof ApiSourcesCountServerRoute
  ApiWebhookPolarServerRoute: typeof ApiWebhookPolarServerRoute
  IntegrationsCalendlyCallbackServerRoute: typeof IntegrationsCalendlyCallbackServerRoute
  ApiActivityIndexServerRoute: typeof ApiActivityIndexServerRoute
  ApiAgentActionsIndexServerRoute: typeof ApiAgentActionsIndexServerRoute
  ApiChatIndexServerRoute: typeof ApiChatIndexServerRoute
  ApiEmbedChatPlatformIdentifierServerRoute: typeof ApiEmbedChatPlatformIdentifierServerRoute
  ApiEmbedChatbotIdentifierServerRoute: typeof ApiEmbedChatbotIdentifierServerRoute
  ApiIntegrationsCalendlyAuthConnectServerRoute: typeof ApiIntegrationsCalendlyAuthConnectServerRoute
  ApiIntegrationsCalendlyAuthDisconnectServerRoute: typeof ApiIntegrationsCalendlyAuthDisconnectServerRoute
  ApiIntegrationsCalendlyAuthRefreshServerRoute: typeof ApiIntegrationsCalendlyAuthRefreshServerRoute
  ApiIntegrationsCalendlySettingsChatbotIdServerRoute: typeof ApiIntegrationsCalendlySettingsChatbotIdServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-plan': {
      id: '/choose-plan'
      path: '/choose-plan'
      fullPath: '/choose-plan'
      preLoaderRoute: typeof ChoosePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk/$pageId': {
      id: '/talk/$pageId'
      path: '/talk/$pageId'
      fullPath: '/talk/$pageId'
      preLoaderRoute: typeof TalkPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bubble/$widgetId': {
      id: '/bubble/$widgetId'
      path: '/bubble/$widgetId'
      fullPath: '/bubble/$widgetId'
      preLoaderRoute: typeof BubbleWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/playground': {
      id: '/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AdminPlaygroundRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/knowledge-base': {
      id: '/admin/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AdminKnowledgeBaseRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat-history/': {
      id: '/admin/chat-history/'
      path: '/chat-history'
      fullPath: '/admin/chat-history'
      preLoaderRoute: typeof AdminChatHistoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity/': {
      id: '/admin/activity/'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/actions/': {
      id: '/admin/actions/'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/actions/new-action': {
      id: '/admin/actions/new-action'
      path: '/actions/new-action'
      fullPath: '/admin/actions/new-action'
      preLoaderRoute: typeof AdminActionsNewActionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/actions/edit-action': {
      id: '/admin/actions/edit-action'
      path: '/actions/edit-action'
      fullPath: '/admin/actions/edit-action'
      preLoaderRoute: typeof AdminActionsEditActionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/vote-count': {
      id: '/api/vote-count'
      path: '/api/vote-count'
      fullPath: '/api/vote-count'
      preLoaderRoute: typeof ApiVoteCountServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/vote': {
      id: '/api/vote'
      path: '/api/vote'
      fullPath: '/api/vote'
      preLoaderRoute: typeof ApiVoteServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/visitor-analytics': {
      id: '/api/visitor-analytics'
      path: '/api/visitor-analytics'
      fullPath: '/api/visitor-analytics'
      preLoaderRoute: typeof ApiVisitorAnalyticsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/upload-images': {
      id: '/api/upload-images'
      path: '/api/upload-images'
      fullPath: '/api/upload-images'
      preLoaderRoute: typeof ApiUploadImagesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/upload-documents': {
      id: '/api/upload-documents'
      path: '/api/upload-documents'
      fullPath: '/api/upload-documents'
      preLoaderRoute: typeof ApiUploadDocumentsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/update-chat-status': {
      id: '/api/update-chat-status'
      path: '/api/update-chat-status'
      fullPath: '/api/update-chat-status'
      preLoaderRoute: typeof ApiUpdateChatStatusServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/training-status': {
      id: '/api/training-status'
      path: '/api/training-status'
      fullPath: '/api/training-status'
      preLoaderRoute: typeof ApiTrainingStatusServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/train-agent': {
      id: '/api/train-agent'
      path: '/api/train-agent'
      fullPath: '/api/train-agent'
      preLoaderRoute: typeof ApiTrainAgentServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/text-sources': {
      id: '/api/text-sources'
      path: '/api/text-sources'
      fullPath: '/api/text-sources'
      preLoaderRoute: typeof ApiTextSourcesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/similarity-search': {
      id: '/api/similarity-search'
      path: '/api/similarity-search'
      fullPath: '/api/similarity-search'
      preLoaderRoute: typeof ApiSimilaritySearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/set-active-chatbot': {
      id: '/api/set-active-chatbot'
      path: '/api/set-active-chatbot'
      fullPath: '/api/set-active-chatbot'
      preLoaderRoute: typeof ApiSetActiveChatbotServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/report-issue': {
      id: '/api/report-issue'
      path: '/api/report-issue'
      fullPath: '/api/report-issue'
      preLoaderRoute: typeof ApiReportIssueServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/my-chatbot': {
      id: '/api/my-chatbot'
      path: '/api/my-chatbot'
      fullPath: '/api/my-chatbot'
      preLoaderRoute: typeof ApiMyChatbotServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/invite-member': {
      id: '/api/invite-member'
      path: '/api/invite-member'
      fullPath: '/api/invite-member'
      preLoaderRoute: typeof ApiInviteMemberServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/firecrawl-webhook': {
      id: '/api/firecrawl-webhook'
      path: '/api/firecrawl-webhook'
      fullPath: '/api/firecrawl-webhook'
      preLoaderRoute: typeof ApiFirecrawlWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/document-source': {
      id: '/api/document-source'
      path: '/api/document-source'
      fullPath: '/api/document-source'
      preLoaderRoute: typeof ApiDocumentSourceServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/crawl': {
      id: '/api/crawl'
      path: '/api/crawl'
      fullPath: '/api/crawl'
      preLoaderRoute: typeof ApiCrawlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/chatbots': {
      id: '/api/chatbots'
      path: '/api/chatbots'
      fullPath: '/api/chatbots'
      preLoaderRoute: typeof ApiChatbotsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/chatbot-count': {
      id: '/api/chatbot-count'
      path: '/api/chatbot-count'
      fullPath: '/api/chatbot-count'
      preLoaderRoute: typeof ApiChatbotCountServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/analytics-stream': {
      id: '/api/analytics-stream'
      path: '/api/analytics-stream'
      fullPath: '/api/analytics-stream'
      preLoaderRoute: typeof ApiAnalyticsStreamServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/agent-actions/': {
      id: '/api/agent-actions/'
      path: '/api/agent-actions'
      fullPath: '/api/agent-actions'
      preLoaderRoute: typeof ApiAgentActionsIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/activity/': {
      id: '/api/activity/'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/integrations/calendly/callback': {
      id: '/integrations/calendly/callback'
      path: '/integrations/calendly/callback'
      fullPath: '/integrations/calendly/callback'
      preLoaderRoute: typeof IntegrationsCalendlyCallbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/sources/count': {
      id: '/api/sources/count'
      path: '/api/sources/count'
      fullPath: '/api/sources/count'
      preLoaderRoute: typeof ApiSourcesCountServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/embed/generate-token': {
      id: '/api/embed/generate-token'
      path: '/api/embed/generate-token'
      fullPath: '/api/embed/generate-token'
      preLoaderRoute: typeof ApiEmbedGenerateTokenServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/chat/history': {
      id: '/api/chat/history'
      path: '/api/chat/history'
      fullPath: '/api/chat/history'
      preLoaderRoute: typeof ApiChatHistoryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/agent-actions/$actionId': {
      id: '/api/agent-actions/$actionId'
      path: '/api/agent-actions/$actionId'
      fullPath: '/api/agent-actions/$actionId'
      preLoaderRoute: typeof ApiAgentActionsActionIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/activity/$activityId': {
      id: '/api/activity/$activityId'
      path: '/api/activity/$activityId'
      fullPath: '/api/activity/$activityId'
      preLoaderRoute: typeof ApiActivityActivityIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/accept-invitation/$invitationId': {
      id: '/api/accept-invitation/$invitationId'
      path: '/api/accept-invitation/$invitationId'
      fullPath: '/api/accept-invitation/$invitationId'
      preLoaderRoute: typeof ApiAcceptInvitationInvitationIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/embed/chatbot/$identifier': {
      id: '/api/embed/chatbot/$identifier'
      path: '/api/embed/chatbot/$identifier'
      fullPath: '/api/embed/chatbot/$identifier'
      preLoaderRoute: typeof ApiEmbedChatbotIdentifierServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/embed/chat/$platformIdentifier': {
      id: '/api/embed/chat/$platformIdentifier'
      path: '/api/embed/chat/$platformIdentifier'
      fullPath: '/api/embed/chat/$platformIdentifier'
      preLoaderRoute: typeof ApiEmbedChatPlatformIdentifierServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/integrations/calendly/settings/$chatbotId': {
      id: '/api/integrations/calendly/settings/$chatbotId'
      path: '/api/integrations/calendly/settings/$chatbotId'
      fullPath: '/api/integrations/calendly/settings/$chatbotId'
      preLoaderRoute: typeof ApiIntegrationsCalendlySettingsChatbotIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/integrations/calendly/auth/refresh': {
      id: '/api/integrations/calendly/auth/refresh'
      path: '/api/integrations/calendly/auth/refresh'
      fullPath: '/api/integrations/calendly/auth/refresh'
      preLoaderRoute: typeof ApiIntegrationsCalendlyAuthRefreshServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/integrations/calendly/auth/disconnect': {
      id: '/api/integrations/calendly/auth/disconnect'
      path: '/api/integrations/calendly/auth/disconnect'
      fullPath: '/api/integrations/calendly/auth/disconnect'
      preLoaderRoute: typeof ApiIntegrationsCalendlyAuthDisconnectServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/integrations/calendly/auth/connect': {
      id: '/api/integrations/calendly/auth/connect'
      path: '/api/integrations/calendly/auth/connect'
      fullPath: '/api/integrations/calendly/auth/connect'
      preLoaderRoute: typeof ApiIntegrationsCalendlyAuthConnectServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminKnowledgeBaseRoute: typeof AdminKnowledgeBaseRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPlaygroundRoute: typeof AdminPlaygroundRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminActionsEditActionRoute: typeof AdminActionsEditActionRoute
  AdminActionsNewActionRoute: typeof AdminActionsNewActionRoute
  AdminActionsIndexRoute: typeof AdminActionsIndexRoute
  AdminActivityIndexRoute: typeof AdminActivityIndexRoute
  AdminChatHistoryIndexRoute: typeof AdminChatHistoryIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminKnowledgeBaseRoute: AdminKnowledgeBaseRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPlaygroundRoute: AdminPlaygroundRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminActionsEditActionRoute: AdminActionsEditActionRoute,
  AdminActionsNewActionRoute: AdminActionsNewActionRoute,
  AdminActionsIndexRoute: AdminActionsIndexRoute,
  AdminActivityIndexRoute: AdminActivityIndexRoute,
  AdminChatHistoryIndexRoute: AdminChatHistoryIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ChoosePlanRoute: ChoosePlanRoute,
  SuccessRoute: SuccessRoute,
  TestRoute: TestRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSetupRoute: authSetupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  BubbleWidgetIdRoute: BubbleWidgetIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  TalkPageIdRoute: TalkPageIdRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAnalyticsStreamServerRoute: ApiAnalyticsStreamServerRoute,
  ApiChatbotCountServerRoute: ApiChatbotCountServerRoute,
  ApiChatbotsServerRoute: ApiChatbotsServerRoute,
  ApiCheckoutServerRoute: ApiCheckoutServerRoute,
  ApiCrawlServerRoute: ApiCrawlServerRoute,
  ApiDocumentSourceServerRoute: ApiDocumentSourceServerRoute,
  ApiFeedbackServerRoute: ApiFeedbackServerRoute,
  ApiFirecrawlWebhookServerRoute: ApiFirecrawlWebhookServerRoute,
  ApiHelloServerRoute: ApiHelloServerRoute,
  ApiInviteMemberServerRoute: ApiInviteMemberServerRoute,
  ApiLeadsServerRoute: ApiLeadsServerRoute,
  ApiMyChatbotServerRoute: ApiMyChatbotServerRoute,
  ApiOgServerRoute: ApiOgServerRoute,
  ApiQuestionsServerRoute: ApiQuestionsServerRoute,
  ApiReportIssueServerRoute: ApiReportIssueServerRoute,
  ApiScrapeServerRoute: ApiScrapeServerRoute,
  ApiSetActiveChatbotServerRoute: ApiSetActiveChatbotServerRoute,
  ApiSimilaritySearchServerRoute: ApiSimilaritySearchServerRoute,
  ApiTextSourcesServerRoute: ApiTextSourcesServerRoute,
  ApiTrainAgentServerRoute: ApiTrainAgentServerRoute,
  ApiTrainingStatusServerRoute: ApiTrainingStatusServerRoute,
  ApiUpdateChatStatusServerRoute: ApiUpdateChatStatusServerRoute,
  ApiUploadDocumentsServerRoute: ApiUploadDocumentsServerRoute,
  ApiUploadImagesServerRoute: ApiUploadImagesServerRoute,
  ApiVisitorAnalyticsServerRoute: ApiVisitorAnalyticsServerRoute,
  ApiVoteServerRoute: ApiVoteServerRoute,
  ApiVoteCountServerRoute: ApiVoteCountServerRoute,
  ApiAcceptInvitationInvitationIdServerRoute:
    ApiAcceptInvitationInvitationIdServerRoute,
  ApiActivityActivityIdServerRoute: ApiActivityActivityIdServerRoute,
  ApiAgentActionsActionIdServerRoute: ApiAgentActionsActionIdServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiChatHistoryServerRoute: ApiChatHistoryServerRoute,
  ApiEmbedGenerateTokenServerRoute: ApiEmbedGenerateTokenServerRoute,
  ApiSourcesCountServerRoute: ApiSourcesCountServerRoute,
  ApiWebhookPolarServerRoute: ApiWebhookPolarServerRoute,
  IntegrationsCalendlyCallbackServerRoute:
    IntegrationsCalendlyCallbackServerRoute,
  ApiActivityIndexServerRoute: ApiActivityIndexServerRoute,
  ApiAgentActionsIndexServerRoute: ApiAgentActionsIndexServerRoute,
  ApiChatIndexServerRoute: ApiChatIndexServerRoute,
  ApiEmbedChatPlatformIdentifierServerRoute:
    ApiEmbedChatPlatformIdentifierServerRoute,
  ApiEmbedChatbotIdentifierServerRoute: ApiEmbedChatbotIdentifierServerRoute,
  ApiIntegrationsCalendlyAuthConnectServerRoute:
    ApiIntegrationsCalendlyAuthConnectServerRoute,
  ApiIntegrationsCalendlyAuthDisconnectServerRoute:
    ApiIntegrationsCalendlyAuthDisconnectServerRoute,
  ApiIntegrationsCalendlyAuthRefreshServerRoute:
    ApiIntegrationsCalendlyAuthRefreshServerRoute,
  ApiIntegrationsCalendlySettingsChatbotIdServerRoute:
    ApiIntegrationsCalendlySettingsChatbotIdServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
